version: '2'

services:
    farstriderServer:
        image: jbrjake/farstrider-server:latest
        links:
            - mongo:mongo
        ports:
            - "80:8080"
    mongo:
        volumes:
            - /data/db
        image: mongo
        expose:
            - "27017"
